# Site
name: "CGM Innovation Hub"
title: "CGM Innovation Hub"
description: "Compugroup Medical Innovation Hub Tech Blog"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /CGM-Innovation-Hub-Tech-Blog
url: "https://studiofarma.github.io"
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  paolo.venturi:
    name: Paolo Venturi
    display_name: Paolo Venturi
    avatar: 'assets/images/avatar/paolo-venturi.jpg'
  luca.piccinelli:
    name: Luca Piccinelli
    display_name: Luca Piccinelli
    avatar: 'assets/images/avatar/luca-piccinelli.jpg'

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
